-- RUN JUST ONCE

DROP DATABASE IF EXISTS my;
CREATE DATABASE my DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON my.* TO 'issue'@'localhost' IDENTIFIED BY 'issue';

FLUSH PRIVILEGES;
